# Generated by Django 4.0.4 on 2022-06-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='asset_name',
            new_name='name',
        ),
    ]
