# Generated by Django 4.0.4 on 2022-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_asset_name_assets_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterFollows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('link', models.URLField(max_length=128, unique=True)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
